repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: Import sorting
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black
        name: Code formatting
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: Code style
        additional_dependencies:
          - pylint_django==2.5.5
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies:
          - Django==4.2.14
          - django-environ==0.11.2
          - mysqlclient==2.2.4
          - bcrypt==4.1.3
          - django-stubs==4.2.7
          - django-admin-autocomplete-filter==0.7.1
          - djangorestframework==3.14.0
          - djangorestframework-stubs==3.14.5
          - djangorestframework-simplejwt==5.3.1

