[tool.poetry]
name = "finance_api"
version = "1.0.0"
description = "Finance services REST API"
authors = ["Jose Solano <jesolano@protonmail.com>"]
readme = "README.md"
packages = [{ include = "finance_api" }]

[tool.ruff.lint]
# Enable import sorting.
extend-select = ["I"]
