# Generated by Django 5.0.4 on 2024-05-26 23:00

import uuid

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("american_express", "American Express"),
                            ("banorte", "Banorte"),
                            ("banco_azteca", "Banco Azteca"),
                            ("hsbc", "Hsbc"),
                            ("banca_coppel", "Banca Coppel"),
                            ("invex_banco", "INVEX Banco"),
                            ("bbva_bancomer", "BBVA Bancomer"),
                            ("konfio_red_amigo_dal", "Konfio Red Amigo DAL"),
                            ("citibanamex", "CitiBanamex"),
                            ("scotiabank", "Scotiabank"),
                            ("santander", "Santander"),
                            ("banco_bajio", "Banco Bajío"),
                            ("inbursa", "Inbursa"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("global_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
