# Generated by Django 5.0.4 on 2024-05-26 18:35

from django.db import migrations

default_banks = (
    ("american_express", "American Express"),
    ("banorte", "Banorte"),
    ("banco_azteca", "Banco Azteca"),
    ("hsbc", "Hsbc"),
    ("banca_coppel", "Banca Coppel"),
    ("invex_banco", "INVEX Banco"),
    ("bbva_bancomer", "BBVA Bancomer"),
    ("konfio_red_amigo_dal", "Konfio Red Amigo DAL"),
    ("citibanamex", "CitiBanamex"),
    ("scotiabank", "Scotiabank"),
    ("santander", "Santander"),
    ("banco_bajio", "Banco Bajío"),
    ("inbursa", "Inbursa"),
)


def insert_default_banks(apps, schema_editor):
    Bank = apps.get_model("bank", "Bank")
    banks = [Bank(code=code, name=name) for code, name in default_banks]
    Bank.global_objects.bulk_create(banks)


def delete_default_banks(apps, schema_editor):
    Bank = apps.get_model("bank", "Bank")
    Bank.global_objects.filter(code__in=default_banks).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0001_create_bank_model"),
    ]

    operations = [migrations.RunPython(insert_default_banks, delete_default_banks)]
