# Generated by Django 5.0.4 on 2024-05-30 03:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0002_insert_default_banks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bank",
            options={"verbose_name": "Bank", "verbose_name_plural": "Banks"},
        ),
        migrations.AlterField(
            model_name="bank",
            name="code",
            field=models.CharField(
                choices=[
                    ("american_express", "American Express"),
                    ("banorte", "Banorte"),
                    ("banco_azteca", "Banco Azteca"),
                    ("hsbc", "Hsbc"),
                    ("banca_coppel", "Banca Coppel"),
                    ("invex_banco", "INVEX Banco"),
                    ("bbva_bancomer", "BBVA Bancomer"),
                    ("konfio_red_amigo_dal", "Konfio Red Amigo DAL"),
                    ("citibanamex", "CitiBanamex"),
                    ("scotiabank", "Scotiabank"),
                    ("santander", "Santander"),
                    ("banco_bajio", "Banco Bajío"),
                    ("inbursa", "Inbursa"),
                ],
                max_length=255,
                unique=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created date"),
        ),
        migrations.AlterField(
            model_name="bank",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deletion date"
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="bank",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="bank",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Update date"),
        ),
        migrations.AlterField(
            model_name="bank",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, verbose_name="UUID"
            ),
        ),
    ]
