- name: Setup database
  hosts: database
  become: true
  tasks:
    - name: Install MySQL
      ansible.builtin.apt:
        name: mysql=8
        state: present
    - name: Create database
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present
    - name: Create user
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        state: present
