# Generated by Django 4.2.14 on 2024-07-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multitenant", "0001_create_tenant_model"),
        ("finance_auth", "0001_create_user_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="tenants",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                related_query_name="user",
                to="multitenant.tenant",
            ),
        ),
    ]
