# Generated by Django 5.0.4 on 2024-06-02 00:36

from django.db import migrations

initial_company_types = [
    ("customer", "Customer"),
    ("supplier", "Supplier"),
    ("creditor", "Creditor"),
    ("employee", "Employee"),
    ("debtor", "Debtor"),
]


def insert_initial_company_types(apps, schema_editor):
    CompanyType = apps.get_model("company", "CompanyType")
    for code, name in initial_company_types:
        CompanyType.global_objects.get_or_create(code=code, name=name)


def delete_initial_company_types(apps, schema_editor):
    CompanyType = apps.get_model("company", "CompanyType")
    for code, _ in initial_company_types:
        CompanyType.global_objects.filter(code=code).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_create_company_and_company_type_models"),
    ]

    operations = [
        migrations.RunPython(insert_initial_company_types, delete_initial_company_types)
    ]
