on:
  pull_request:
    branches: ["main"]

jobs:
  lint-format-check:
    name: Code Static Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Check imports sorting
        uses: isort/isort-action@master
        with:
          isortVersion: "5.13.2"
      - name: Check code formatting
        uses: psf/black@stable
        with:
          version: "24.4.2"
      - name: Check code style
        uses: py-actions/flake8@v2
        with:
          flake8-version: "7.0.0"
          plugins: "pylint_django==2.5.5"
