on: workflow_dispatch
jobs:
  staging-database-setup:
    name: Staging Database Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"
      - name: Install Ansible
        run: pip install ansible==9.5.1
      - name: Create SSH Key file
        run: echo "${{ secrets.STAGING_SSH }}" > .ansible_key
      - name: Setup known_hosts
        run: ssh-keyscan "${{ secrets.STAGING_DB_HOST }}" >> ~/.ssh/known_hosts
      - name: Create Ansible Inventory file
        run: |
          sed -i "s/$DB_HOST/${{ secrets.STAGING_DB_HOST }}/g" \
          deployment/inventory/staging
      - name: Run Ansible playbook
        run: |
          ansible-playbook deployment/playbooks/database.yaml \
          --key-file .ansible_key \
          -i deployment/inventory/staging \
          -e @deployment/vars/staging.yaml \
