on: workflow_dispatch
jobs:
  staging-database-setup:
    name: Staging Database Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: "pip"
      - name: Install Ansible
        run: pip install ansible==9.5.1
      - name: Create SSH Key file
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > .ansible_key
          chmod 600 .ansible_key
      - name: Setup .ssh
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts
      - name: Create Ansible Inventory file
        run: |
          sed -i "s/\$DB_HOST/${{ secrets.SERVER_HOST }}/g" \
          devops/inventory/staging
      - name: Run Ansible playbook
        run: |
          ansible-playbook devops/playbooks/database.yaml \
          --key-file .ansible_key \
          --user "${{ secrets.SERVER_USER }}" \
          -i devops/inventory/staging \
          -e @devops/vars/staging.yaml \
